# Site settings
title: Diary of a Madman
email: krivich.ekaterina@gmail.com
description: ""
baseurl: ""
url: "http://kiote.github.io"
twitter_username: kiote
github_username:  kiote

# Build settings
markdown: kramdown
permalink: pretty
